using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace GeneralUpdate.Tools.Services;

/// <summary>
/// Simple dictionary-based localization. Supports zh-CN and en-US.
/// Usage: LocalizationService.Instance["Patch.Title"]
/// </summary>
public class LocalizationService : INotifyPropertyChanged
{
    public static LocalizationService Instance { get; } = new();

    private string _locale = "zh-CN";

    public string Locale
    {
        get => _locale;
        set
        {
            if (_locale != value)
            {
                _locale = value;
                OnPropertyChanged();
                OnPropertyChanged("Item");
            }
        }
    }

    public string this[string key]
    {
        get
        {
            if (_strings.TryGetValue(_locale, out var langDict) && langDict.TryGetValue(key, out var val))
                return val;
            // Fallback to zh-CN
            if (_locale != "zh-CN" && _strings.TryGetValue("zh-CN", out var fallback) &&
                fallback.TryGetValue(key, out var fb))
                return fb;
            return key;
        }
    }

    private readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["zh-CN"] = new()
        {
            ["App.Title"] = "GeneralUpdate Tools",
            ["Nav.Patch"] = "补丁包",
            ["Nav.Extension"] = "扩展包",
            ["Nav.OSS"] = "OSS配置",
            ["Patch.Title"] = "补丁包生成",
            ["Patch.CorePaths"] = "核心路径",
            ["Patch.OldDir"] = "旧版本目录",
            ["Patch.NewDir"] = "新版本目录",
            ["Patch.Select"] = "选择",
            ["Patch.OldPlaceholder"] = "选择旧版本应用目录...",
            ["Patch.NewPlaceholder"] = "选择新版本发布目录...",
            ["Patch.PackageInfo"] = "包信息",
            ["Patch.PackageName"] = "包名",
            ["Patch.Version"] = "版本",
            ["Patch.OutputDir"] = "输出目录",
            ["Patch.OutputPlaceholder"] = "桌面 (默认)",
            ["Patch.Build"] = "开始构建",
            ["Patch.Ready"] = "就绪",
            ["Patch.ValidateDirs"] = "请选择新旧版本目录",
            ["Patch.Building"] = "正在生成差分补丁...",
            ["Patch.Comparing"] = "对比目录差异 + 生成补丁...",
            ["Patch.PatchDone"] = "补丁生成完成",
            ["Patch.Packing"] = "打包: {0}",
            ["Patch.Success"] = "成功: {0} ({1:F1} KB)",
            ["Patch.Failed"] = "失败: {0}",
            ["Patch.Error"] = "错误: {0}",
            ["Patch.InvalidVersion"] = "版本号 '{0}' 不符合 semver 规范 (https://semver.org/lang/zh-CN/)。示例: 1.0.0",
            ["Patch.OldSelected"] = "旧版本: {0}",
            ["Patch.NewSelected"] = "新版本: {0}",
            ["Patch.TempDir"] = "临时目录: {0}",
            ["Patch.EncryptionCheck"] = "打包前检测加密文件",
            ["Patch.EncryptionCheckTip"] = "扫描补丁包中是否包含被加密/加壳的文件",
            ["Patch.Scanning"] = "正在扫描加密文件...",
            ["Patch.ScanFound"] = "检测到 {0} 个可疑文件",
            ["Patch.ScanClean"] = "未检测到加密文件",
            ["Patch.ScanDialogTitle"] = "⚠️ 检测到加密/可疑文件",
            ["Patch.ScanDialogHeader"] = "以下文件可能存在加密或加壳保护，打包后可能导致客户端更新失败：",
            ["Patch.ScanHighRisk"] = "🔴 高风险",
            ["Patch.ScanMediumRisk"] = "🟡 中风险",
            ["Patch.ScanLowRisk"] = "⚪ 低风险",
            ["Patch.ScanFilesScanned"] = "共扫描 {0} 个文件",
            ["Patch.ScanBtnSkip"] = "跳过可疑文件，继续打包",
            ["Patch.ScanBtnInclude"] = "仍然打包全部文件",
            ["Patch.ScanBtnCancel"] = "取消",
            ["Patch.ScanSkipped"] = "已跳过 {0} 个可疑文件",
            ["Ext.Title"] = "扩展包生成",
            ["Ext.BasicInfo"] = "基本信息",
            ["Ext.Name"] = "名称",
            ["Ext.Version"] = "版本",
            ["Ext.Description"] = "描述",
            ["Ext.DescPlaceholder"] = "扩展功能描述...",
            ["Ext.Publisher"] = "发布者",
            ["Ext.License"] = "许可证",
            ["Ext.LicensePlaceholder"] = "MIT",
            ["Ext.Paths"] = "路径",
            ["Ext.ExtDir"] = "扩展目录",
            ["Ext.ExportDir"] = "导出目录",
            ["Ext.CustomProps"] = "自定义属性",
            ["Ext.Key"] = "Key",
            ["Ext.Value"] = "Value",
            ["Ext.AddProp"] = "+ 添加",
            ["Ext.Generate"] = "生成扩展包",
            ["Ext.ValidateNameVer"] = "请填写扩展名称和版本",
            ["Ext.InvalidVersion"] = "版本号 '{0}' 不符合 semver 规范。示例: 1.0.0",
            ["Ext.ValidateDir"] = "请选择有效的扩展目录",
            ["Ext.Building"] = "正在生成扩展包...",
            ["Ext.Success"] = "成功: {0}",
            ["Ext.Failed"] = "失败: {0}",
            ["OSS.Title"] = "OSS 配置生成",
            ["OSS.NewEntry"] = "新建条目",
            ["OSS.PacketName"] = "包名",
            ["OSS.Version"] = "版本",
            ["OSS.Url"] = "URL",
            ["OSS.SHA256"] = "SHA256",
            ["OSS.ComputeHash"] = "计算",
            ["OSS.AddToList"] = "添加到列表",
            ["OSS.ConfigList"] = "配置列表",
            ["OSS.Clear"] = "清空",
            ["OSS.Export"] = "导出 JSON",
            ["OSS.Added"] = "已添加",
            ["OSS.Cleared"] = "已清空",
            ["OSS.Exported"] = "导出: {0} 条",
            ["OSS.HashResult"] = "SHA256: {0}",
            ["OSS.InvalidVersion"] = "版本号 '{0}' 不符合 semver 规范。示例: 1.0.0",
            ["Theme.Light"] = "浅色",
            ["Theme.Dark"] = "深色",
            ["Theme.Toggle"] = "切换主题",
            ["Nav.Simulate"] = "模拟更新",
            ["Sim.Title"] = "模拟更新",
            ["Sim.TestTarget"] = "测试目标",
            ["Sim.OldAppDir"] = "旧版本应用目录",
            ["Sim.PatchFile"] = "补丁包文件",
            ["Sim.Select"] = "选择",
            ["Sim.UpdateConfig"] = "更新配置",
            ["Sim.CurrentVer"] = "当前版本",
            ["Sim.TargetVer"] = "目标版本",
            ["Sim.Platform"] = "平台",
            ["Sim.AppType"] = "应用类型",
            ["Sim.AppSecret"] = "应用密钥",
            ["Sim.ProductId"] = "产品ID",
            ["Sim.UpdatePath"] = "更新路径",
            ["Sim.Output"] = "输出",
            ["Sim.OutputDir"] = "模拟目录",
            ["Sim.Start"] = "开始模拟",
            ["Sim.SelectAppDir"] = "选择旧版本应用目录",
            ["Sim.SelectPatch"] = "选择补丁包",
            ["Sim.SelectOutput"] = "选择模拟输出目录",
            ["Sim.ValidateDirs"] = "请填写所有必填项",
            ["Sim.InvalidVersion"] = "版本号 '{0}' 不符合 semver 规范。示例: 1.0.0",
            ["Sim.DotnetCheck"] = "需要 .NET 10.0 SDK，请先安装",
            ["Sim.AutoRun"] = "自动启动服务器并运行客户端",
            ["Sim.ManualMode"] = "服务器/客户端已生成，可手动运行:\ndotnet script client.csx",
            ["Sim.Starting"] = "正在启动模拟...",
            ["Sim.Completed"] = "模拟完成 ({0:F1}s)",
            ["Sim.Failed"] = "模拟失败: {0}",
            ["Sim.Report"] = "报告: {0}",

            // ── Config Generator ──
            ["Nav.Config"] = "配置生成",
            ["Config.Title"] = "配置生成器",
            ["Config.ClientPath"] = "Client 项目 (.csproj)",
            ["Config.UpgradePath"] = "Upgrade 项目 (.csproj)",
            ["Config.Browse"] = "浏览",
            ["Config.BrowseClient"] = "选择 Client 项目文件",
            ["Config.BrowseUpgrade"] = "选择 Upgrade 项目文件",
            ["Config.Analyze"] = "分析",
            ["Config.Analyzing"] = "正在分析...",
            ["Config.Analyzed"] = "分析完成",
            ["Config.Fields"] = "配置字段",
            ["Config.AutoAnalyzed"] = "── 自动分析（AssemblyName）──",
            ["Config.ManualInput"] = "── 手动输入（版本号需符合 semver）──",
            ["Config.MainAppName"] = "主程序名称",
            ["Config.ClientVersion"] = "主程序版本",
            ["Config.UpdateAppName"] = "升级器名称",
            ["Config.UpgradeClientVersion"] = "升级器版本",
            ["Config.AppType"] = "应用类型",
            ["Config.ProductId"] = "产品 ID",
            ["Config.UpdatePath"] = "升级器子目录",
            ["Config.Generate"] = "生成配置文件",
            ["Config.Generated"] = "已生成配置文件",
            ["Config.GenerateSample"] = "生成示例项目结构",
            ["Config.SampleGenerated"] = "示例已生成",
            ["Config.Publishing"] = "正在 dotnet publish...",
            ["Config.Preview"] = "JSON 预览",
            ["Config.CodeHint"] = "new GeneralUpdateBootstrap()\n    .SetSource(\"https://...\", \"your-key\", \"your-token\", \"https\")\n    .LaunchAsync();",
            ["Config.NoClientPath"] = "请选择 Client 项目路径",
            ["Config.Failed"] = "失败",
            ["Config.OpenManifestDir"] = "生成后打开 manifest.json 所在目录",
            ["Config.OpenSampleDir"] = "生成后打开示例项目结构目录",
        },
        ["en-US"] = new()
        {
            ["App.Title"] = "GeneralUpdate Tools",
            ["Nav.Patch"] = "Patch",
            ["Nav.Extension"] = "Extension",
            ["Nav.OSS"] = "OSS Config",
            ["Patch.Title"] = "Patch Package",
            ["Patch.CorePaths"] = "Core Paths",
            ["Patch.OldDir"] = "Old Directory",
            ["Patch.NewDir"] = "New Directory",
            ["Patch.Select"] = "Select",
            ["Patch.OldPlaceholder"] = "Select old version directory...",
            ["Patch.NewPlaceholder"] = "Select new version directory...",
            ["Patch.PackageInfo"] = "Package Info",
            ["Patch.PackageName"] = "Package Name",
            ["Patch.Version"] = "Version",
            ["Patch.OutputDir"] = "Output Directory",
            ["Patch.OutputPlaceholder"] = "Desktop (default)",
            ["Patch.Build"] = "Build",
            ["Patch.Ready"] = "Ready",
            ["Patch.ValidateDirs"] = "Please select both old and new directories",
            ["Patch.Building"] = "Generating diff patch...",
            ["Patch.Comparing"] = "Comparing directories + generating patches...",
            ["Patch.PatchDone"] = "Patch generation complete",
            ["Patch.Packing"] = "Packing: {0}",
            ["Patch.Success"] = "Success: {0} ({1:F1} KB)",
            ["Patch.Failed"] = "Failed: {0}",
            ["Patch.Error"] = "Error: {0}",
            ["Patch.InvalidVersion"] = "Version '{0}' does not follow semver. Example: 1.0.0",
            ["Patch.OldSelected"] = "Old version: {0}",
            ["Patch.NewSelected"] = "New version: {0}",
            ["Patch.TempDir"] = "Temp directory: {0}",
            ["Patch.EncryptionCheck"] = "Scan for encrypted files before packaging",
            ["Patch.EncryptionCheckTip"] = "Detect encrypted/packed files in the patch package",
            ["Patch.Scanning"] = "Scanning for encrypted files...",
            ["Patch.ScanFound"] = "Found {0} suspicious file(s)",
            ["Patch.ScanClean"] = "No encrypted files detected",
            ["Patch.ScanDialogTitle"] = "⚠️ Encrypted / Suspicious Files Detected",
            ["Patch.ScanDialogHeader"] = "The following files may be encrypted or packed, which could cause client update failures:",
            ["Patch.ScanHighRisk"] = "🔴 High Risk",
            ["Patch.ScanMediumRisk"] = "🟡 Medium Risk",
            ["Patch.ScanLowRisk"] = "⚪ Low Risk",
            ["Patch.ScanFilesScanned"] = "Scanned {0} file(s) total",
            ["Patch.ScanBtnSkip"] = "Skip suspicious files and continue",
            ["Patch.ScanBtnInclude"] = "Include all files anyway",
            ["Patch.ScanBtnCancel"] = "Cancel",
            ["Patch.ScanSkipped"] = "Skipped {0} suspicious file(s)",
            ["Ext.Title"] = "Extension Package",
            ["Ext.BasicInfo"] = "Basic Info",
            ["Ext.Name"] = "Name",
            ["Ext.Version"] = "Version",
            ["Ext.Description"] = "Description",
            ["Ext.DescPlaceholder"] = "Extension description...",
            ["Ext.Publisher"] = "Publisher",
            ["Ext.License"] = "License",
            ["Ext.LicensePlaceholder"] = "MIT",
            ["Ext.Paths"] = "Paths",
            ["Ext.ExtDir"] = "Extension Directory",
            ["Ext.ExportDir"] = "Export Directory",
            ["Ext.CustomProps"] = "Custom Properties",
            ["Ext.Key"] = "Key",
            ["Ext.Value"] = "Value",
            ["Ext.AddProp"] = "+ Add",
            ["Ext.Generate"] = "Generate Extension",
            ["Ext.ValidateNameVer"] = "Please fill in extension name and version",
            ["Ext.InvalidVersion"] = "Version '{0}' does not follow semver. Example: 1.0.0",
            ["Ext.ValidateDir"] = "Please select a valid extension directory",
            ["Ext.Building"] = "Generating extension package...",
            ["Ext.Success"] = "Success: {0}",
            ["Ext.Failed"] = "Failed: {0}",
            ["OSS.Title"] = "OSS Config Generator",
            ["OSS.NewEntry"] = "New Entry",
            ["OSS.PacketName"] = "Package Name",
            ["OSS.Version"] = "Version",
            ["OSS.Url"] = "URL",
            ["OSS.SHA256"] = "SHA256",
            ["OSS.ComputeHash"] = "Compute",
            ["OSS.AddToList"] = "Add to List",
            ["OSS.ConfigList"] = "Config List",
            ["OSS.Clear"] = "Clear",
            ["OSS.Export"] = "Export JSON",
            ["OSS.Added"] = "Added",
            ["OSS.Cleared"] = "Cleared",
            ["OSS.Exported"] = "Exported: {0} entries",
            ["OSS.HashResult"] = "SHA256: {0}",
            ["OSS.InvalidVersion"] = "Version '{0}' does not follow semver. Example: 1.0.0",
            ["Theme.Light"] = "Light",
            ["Theme.Dark"] = "Dark",
            ["Theme.Toggle"] = "Toggle Theme",
            ["Nav.Simulate"] = "Simulate",
            ["Sim.Title"] = "Simulate Update",
            ["Sim.TestTarget"] = "Test Target",
            ["Sim.OldAppDir"] = "Old App Directory",
            ["Sim.PatchFile"] = "Patch Package",
            ["Sim.Select"] = "Select",
            ["Sim.UpdateConfig"] = "Update Config",
            ["Sim.CurrentVer"] = "Current Version",
            ["Sim.TargetVer"] = "Target Version",
            ["Sim.Platform"] = "Platform",
            ["Sim.AppType"] = "App Type",
            ["Sim.AppSecret"] = "App Secret",
            ["Sim.ProductId"] = "Product ID",
            ["Sim.UpdatePath"] = "Update Path",
            ["Sim.Output"] = "Output",
            ["Sim.OutputDir"] = "Simulate Directory",
            ["Sim.Start"] = "Start Simulation",
            ["Sim.SelectAppDir"] = "Select old version directory",
            ["Sim.SelectPatch"] = "Select patch package",
            ["Sim.SelectOutput"] = "Select simulation output directory",
            ["Sim.ValidateDirs"] = "Please fill in all required fields",
            ["Sim.InvalidVersion"] = "Version '{0}' does not follow semver. Example: 1.0.0",
            ["Sim.DotnetCheck"] = ".NET 10.0 SDK is required. Please install it first.",
            ["Sim.AutoRun"] = "Auto-start server and run client",
            ["Sim.ManualMode"] = "Server/client generated. Run manually:\ndotnet script client.csx",
            ["Sim.Starting"] = "Starting simulation...",
            ["Sim.Completed"] = "Simulation completed ({0:F1}s)",
            ["Sim.Failed"] = "Simulation failed: {0}",
            ["Sim.Report"] = "Report: {0}",

            // ── Config Generator ──
            ["Nav.Config"] = "Config",
            ["Config.Title"] = "Config Generator",
            ["Config.ClientPath"] = "Client Project (.csproj)",
            ["Config.UpgradePath"] = "Upgrade Project (.csproj)",
            ["Config.Browse"] = "Browse",
            ["Config.BrowseClient"] = "Select Client project file",
            ["Config.BrowseUpgrade"] = "Select Upgrade project file",
            ["Config.Analyze"] = "Analyze",
            ["Config.Analyzing"] = "Analyzing...",
            ["Config.Analyzed"] = "Analysis complete",
            ["Config.Fields"] = "Configuration Fields",
            ["Config.AutoAnalyzed"] = "-- Auto-analyzed (AssemblyName) --",
            ["Config.ManualInput"] = "-- Manual input (version must follow semver) --",
            ["Config.MainAppName"] = "Main App Name",
            ["Config.ClientVersion"] = "Client Version",
            ["Config.UpdateAppName"] = "Upgrade App Name",
            ["Config.UpgradeClientVersion"] = "Upgrade Version",
            ["Config.AppType"] = "App Type",
            ["Config.ProductId"] = "Product ID",
            ["Config.UpdatePath"] = "Upgrade Subdirectory",
            ["Config.Generate"] = "Generate Config",
            ["Config.Generated"] = "Config file generated",
            ["Config.GenerateSample"] = "Generate Sample Structure",
            ["Config.SampleGenerated"] = "Sample generated",
            ["Config.Publishing"] = "Running dotnet publish...",
            ["Config.Preview"] = "JSON Preview",
            ["Config.CodeHint"] = "new GeneralUpdateBootstrap()\n    .SetSource(\"https://...\", \"your-key\", \"your-token\", \"https\")\n    .LaunchAsync();",
            ["Config.NoClientPath"] = "Please select Client project path",
            ["Config.Failed"] = "Failed",
            ["Config.OpenManifestDir"] = "Open manifest.json folder after generation",
            ["Config.OpenSampleDir"] = "Open sample structure folder after generation",
        }
    };

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? name = null) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));

    public string T(string key) => this[key];
    public string T(string key, params object[] args) => string.Format(this[key], args);
}