using CommunityToolkit.Mvvm.ComponentModel;

namespace GeneralUpdate.Tools.Models;

public record PlatformItem(int Value, string DisplayName) { public override string ToString() => DisplayName; }
public record AppTypeItem(int Value, string DisplayName) { public override string ToString() => DisplayName; }

/// <summary>
/// Configuration for the simulate-update module.
/// </summary>
public partial class SimulateConfigModel : ObservableObject
{
    /// <summary>User-provided old-version app directory to test against.</summary>
    [ObservableProperty] private string _appDirectory = string.Empty;

    /// <summary>Path to a patch .zip generated by the Patch module.</summary>
    [ObservableProperty] private string _patchFilePath = string.Empty;

    /// <summary>The current version of the app being tested.</summary>
    [ObservableProperty] private string _currentVersion = "1.0.0.0";

    /// <summary>The target version the patch upgrades to.</summary>
    [ObservableProperty] private string _targetVersion = "2.0.0.0";

    /// <summary>Platform selector.</summary>
    [ObservableProperty] private PlatformItem _platform = new(1, "Windows");

    /// <summary>AppType selector.</summary>
    [ObservableProperty] private AppTypeItem _appType = new(1, "ClientApp");

    /// <summary>Application secret key for the update API.</summary>
    [ObservableProperty] private string _appSecretKey = "dfeb5833-975e-4afb-88f1-6278ee9aeff6";

    /// <summary>Product identifier.</summary>
    [ObservableProperty] private string _productId = "2d974e2a-31e6-4887-9bb1-b4689e98c77a";

    /// <summary>Directory where client.cs / upgrade.cs and server are generated.</summary>
    [ObservableProperty] private string _outputDirectory = string.Empty;

    /// <summary>Server port assigned at runtime (set by SimulationService).</summary>
    public int ServerPort { get; set; } = 5000;
}
