using CommunityToolkit.Mvvm.ComponentModel;

namespace GeneralUpdate.Tools.Models;

/// <summary>
/// Configuration for the simulate-update module.
/// </summary>
public partial class SimulateConfigModel : ObservableObject
{
    /// <summary>User-provided old-version app directory to test against.</summary>
    [ObservableProperty] private string _appDirectory = string.Empty;

    /// <summary>Path to a patch .zip generated by the Patch module.</summary>
    [ObservableProperty] private string _patchFilePath = string.Empty;

    /// <summary>The current version of the app being tested.</summary>
    [ObservableProperty] private string _currentVersion = "1.0.0.0";

    /// <summary>The target version the patch upgrades to.</summary>
    [ObservableProperty] private string _targetVersion = "2.0.0.0";

    /// <summary>Platform selector (1=Windows, 2=Linux).</summary>
    [ObservableProperty] private int _platform = 1;

    /// <summary>AppType sent to the server (1=ClientApp, 2=UpgradeApp).</summary>
    [ObservableProperty] private int _appType = 1;

    /// <summary>Application secret key for the update API.</summary>
    [ObservableProperty] private string _appSecretKey = "dfeb5833-975e-4afb-88f1-6278ee9aeff6";

    /// <summary>Product identifier.</summary>
    [ObservableProperty] private string _productId = "2d974e2a-31e6-4887-9bb1-b4689e98c77a";

    /// <summary>Directory where client.cs / upgrade.cs and server are generated.</summary>
    [ObservableProperty] private string _outputDirectory = string.Empty;
}
